### ISSUE TITLE
Cannot run on Ubuntu 17.10

### ISSUE THREAD

**Issue by Kukks** [straks/straks#1]
Been trying to run the precompiled version on Ubuntu 17.10 with no success. 

`./straks-qt: error while loading shared libraries: libprotobuf.so.9: cannot open shared object file: No such file or directory`

Before that I had the same error but for libboost 1.58 and also qrencode but I fixed those by installing the packages for them manually but this seems to be an endless cycle. I just downloaded the latest binaries of vertcoin and litecoin and they ran straight away with no issues.

**Comment by squbs** [comment]
You are comparing apples to oranges.  Both of those mentioned coins use dated code split from Bitcoin years ago.
Use this script:  https://github.com/straks/straks/blob/master/contrib/install-dependencies-debian.sh

Make sure you meet all dependencies.  I've had it running on 17.04 without any issues.  Not sure about 17.10.

**Comment by Kukks** [comment]
@squbs Thanks for the reply. Unfortunately even after running that script and building from source, I still get the error when running either the pre-compiled binaries or my fresh build.

A quick `locate` seems to indicate I have `libprotobuf.so.10` instead. Any ideas on how I should proceed? I'm still fresh to the Linux world so please forgive me if I say stupid shit. :)

**Comment by squbs** [comment]
You'll need to compile from source.  Follow build instructions.
