### ISSUE TITLE
OpenSSL version too old

### ISSUE THREAD

**Issue by mythrill** [straks/straks#14]
Just a basic review of the source code highlights the same issue signatum had, it's once again based on an old code base - this is using an even older version of OpenSSL - Signatum uses 1.0.1j - this project uses 1.0.1c - the issue is with bignum, and it was already solved by the bitcoin devs and I already posted the links to the pull request - are there plans to upgrade? (wondering if I will even get a response this time...)

the issues is that the pointer to the private key is directly accessible in memory - I assumed this project was using up to date code, IT IS NOT! - is this going to be reviewed as the recently disclosed Meltdown and Spectre vulnerabilities make this issue even more pertinent.

https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/version_id-141776/Openssl-Openssl-1.0.1c.html

https://www.theguardian.com/technology/2018/jan/04/meltdown-spectre-worst-cpu-bugs-ever-found-affect-computers-intel-processors-security-flaw

**Comment by squbs** [comment]
You have misread or misunderstood the compilation process.  OpenSSL for the binaries submitted are dynamically linked to system specific libraries, so you may need to update your own version if you are compiling.

Moreover, STRAKS is based off Bitcoin version 0.14.2.  Bitcoin core version release 0.12 did away with OpenSSL more or less (https://bitcoincore.org/en/2016/02/23/release-0.12.0/): 

"A new ECDSA signature validation library called libsecp256k1 has been developed by members of the Bitcoin Core team and plugged in as a replacement for OpenSSL. It is the result of almost 3 years of complex engineering, and with this integration, the attack surface for signature validation code has been greatly reduced."

Acknowledged that some of the docs may need updating.

**Comment by mythrill** [comment]
thanks for the quick reply, yes it's in the docs and there are bignum.h references throughout but I did see some have been modified - I will check the released binaries and go through the build process to confirm for myself. Glad to get the feed back :-)
