### ISSUE TITLE
`walletpassphrase` does not unlock wallet from command line but it works in wallet's console interface (osx)

### ISSUE THREAD

**Issue by maml** [straks/straks#16]
**Operating System**: macOS Sierra 10.12.6
**Wallet**: STRAKS Core version v1.14.6.2-18582bd-dirty (64-bit)

Attempting to unlock my wallet from command line with:

`straks-cli walletpassphrase "my-passphrase" 60`

returns

`error code: -14`
`error message:`
`Error: The wallet passphrase entered was incorrect.`

But when I do it from the wallet's console with:

`walletpassphrase "my-passphrase" 60`

it works just fine.

Is this by design?

(`straks-cli`, `straksd`, and `straks-tx` installed to `/usr/local/bin`, all available to my path.)

**Comment by squbs** [comment]
If your passphrase contains spaces, or special characters, you will need to wrap the password within single quotes (') when using the command line utility:

```./straks-cli walletpassphrase 'your-passphrase' 60```

**Comment by maml** [comment]
👍 yep that works. thanks @squbs
