### ISSUE TITLE
Straks-QT sync dialog doesn't show sync progress in dialog window

### ISSUE THREAD

**Issue by eskodhi** [straks/straks#4]
OS: Windows 10 Pro N
Straks Version: 1.14.5.0-Win64

![image](https://user-images.githubusercontent.com/8595564/33104573-df7bdbec-cef6-11e7-8dcd-72b8bba04e88.png)

**Progress** under **Last Block Time** always stays at `100.00%` regardless of what is shown in status bar.

**Comment by dahifi** [comment]
Mine is doing the same, but the last block time is progressing at least.

**Comment by squbs** [comment]
Fixed. Added chaintxdata.
